[project]
name = 'dst-server'
readme = 'README.md'
version = '0.3'
authors = [{ name = 'WH-2099', email = 'wh2099@outlook.com' }]
description = '饥荒专服房间管理'
requires-python = '>=3.13'
dependencies = ['aiohttp', 'beautifulsoup4', 'pydantic']
