name: Build and Push Image

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  latest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build Image
        id: build
        uses: redhat-actions/buildah-build@v2
        with:
          image: dst-server
          tags: latest
          containerfiles: |
            Containerfile

      - name: Push To Registry
        id: push
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build.outputs.image }}
          tags: ${{ steps.build.outputs.tags }}
          registry: docker.io/wh2099
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

  beta:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build Image
        id: build
        uses: redhat-actions/buildah-build@v2
        with:
          image: dst-server
          tags: beta
          containerfiles: |
            Containerfile
          build-args: |
            BETA=1

      - name: Push To Registry
        id: push
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build.outputs.image }}
          tags: ${{ steps.build.outputs.tags }}
          registry: docker.io/wh2099
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}